name: audio_streamer_example
description: Demonstrates how to use the audio_streamer plugin.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.0.0  
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  audio_streamer:
    path: ../

flutter:
  uses-material-design: true
